// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN7vs3fJ95bCMoTViCmlqjDGePSL-SbeM',
    appId: '1:297290592347:web:d50e5c5a4f04d8cf708f7e',
    messagingSenderId: '297290592347',
    projectId: 'notificationtutorial-4d348',
    authDomain: 'notificationtutorial-4d348.firebaseapp.com',
    storageBucket: 'notificationtutorial-4d348.appspot.com',
    measurementId: 'G-WNNXD1EC36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZchhshaItmBEW1PaR8xC1z5w8kogy47E',
    appId: '1:297290592347:android:95fc7d2e92283247708f7e',
    messagingSenderId: '297290592347',
    projectId: 'notificationtutorial-4d348',
    storageBucket: 'notificationtutorial-4d348.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_azfxGWnfb5Qhi3hO8PoAELzezXMzxsM',
    appId: '1:297290592347:ios:5674b3467b766610708f7e',
    messagingSenderId: '297290592347',
    projectId: 'notificationtutorial-4d348',
    storageBucket: 'notificationtutorial-4d348.appspot.com',
    iosBundleId: 'com.example.notificacionestutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_azfxGWnfb5Qhi3hO8PoAELzezXMzxsM',
    appId: '1:297290592347:ios:4634e097de0a4d09708f7e',
    messagingSenderId: '297290592347',
    projectId: 'notificationtutorial-4d348',
    storageBucket: 'notificationtutorial-4d348.appspot.com',
    iosBundleId: 'com.example.notificacionestutorial.RunnerTests',
  );
}
